baseURL = "https://EspenBerget.github.io/"
languageCode = "en-us"
title = "Espen Berget's Coding Blog"



# theme 
theme = "m10c"
[params]
avatar = "images/me.png"
author = "Espen Berget"
description = "Computer programmer, interested in functional programming, web development, and the nix eco-system."

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/EspenBerget"